pipeline {
    agent none
    environment {
        //TODO: Edit these vars as per your env
        DEV_PROJECT = "book-dev"
        STAGE_PROJECT = "book-stage"
        APP_GIT_URL = "https://github.com/yusufalafid/books"

        // DO NOT CHANGE THE GLOBAL VARS BELOW THIS LINE
        APP_NAME = "books"
    }
    stages {
        stage('Build'){
            //agent {
            //   node { label 'agent-0-ssh-slave' }
            //}
            steps{
               sh 'npm install'
            }
        }
        stage('Run Unit Test'){
            //agent {
            //   node { label 'agent-0-ssh-slave' }
            //}
            steps{
               sh 'npm test'
            }
        }
    }
}
